### PR TITLE
Properly serialize bytes

### PR DESCRIPTION
**Pull request by EnTeQuAk**
I somehow forgot to make this pull request. This adds support for serializing ``BinaryField``, please let me know what you think :smiley:

### CODE REVIEW

**Comment by pennersr** [comment]
This breaks the build. Also wondering why unittest2 is included as part of this.

**Comment by EnTeQuAk** [comment]
@pennersr the ``unittest2`` depdency is there because of the ``skipUnless`` usage. Regarding the breaking build, I'll look at this and fix it. Might have messed up the merge.

**Comment by EnTeQuAk** [comment]
@pennersr I just merged with recent master and tests do run locally at least

```
[git:bugfix/serialize-bytes (django-allauth)] ~/Projects/django-allauth> python manage.py test
Creating test database for alias 'default'...
.......................................................................................................................................................................................
----------------------------------------------------------------------
Ran 183 tests in 13.147s
```

The broken builds on travis don't seem to be related to this branch.

**Comment by pennersr** [comment]
I have not found the time to look into this yet. Though, at first glance it seems as base64 encoded strings end up in the wrong place:

    File "/home/travis/build/pennersr/django-allauth/allauth/socialaccount/providers/__init__.py", line 23,     in by_id
        return self.provider_map[id]
    KeyError: u'Yml0bHk='

So that looks suspicious given that you are doing base64 encoding (and master build is passing).

**Comment by EnTeQuAk** [comment]
Ahhhh, I think I found it. I'll fix this later

**Pull request closed without merging**
