### PR TITLE
chore: switch linting and formatting to ruff

### PR DESCRIPTION
**Pull request by akx**
This PR proposes to switch the linting + formatting toolchain from flake8 + isort + black to [Ruff](https://github.com/astral-sh/ruff), a fast, very capable linter + formatter. 

I didn't enable any Ruff rules beyond those that were already enabled by the flake8 + isort configuration.

### CODE REVIEW

**Comment by pennersr** [comment]
See: https://github.com/pennersr/django-allauth/pull/3291#issuecomment-1491998363

**Comment by akx** [comment]
Hah, I had forgotten I'd proposed this last year. A lot of stuff has happened in Ruff land since, though – it now does formatting too :)

**Comment by pennersr** [comment]
No problem. The issue of the binary seems to be unresolved though...

**Comment by akx** [comment]
Well, it _is_ a Rust binary, but they're shipping `musllinux` wheels now too, if that helps.

**Comment by akx** [comment]
What is the issue with pip installing the binary? 🤔 You end up doing that for e.g. `cryptography` too (though an .so in that case, not an executable).

**Comment by pennersr** [comment]
This: https://github.com/astral-sh/ruff/issues/1699

**Pull request closed without merging**
