### PR TITLE
adds mock >= 1.0.1 to requirements.txt

### LINKED ISSUE #838: no module named mock
cloned from  github then ran `pip install -r requirements.txt`

```
$ python manage.py test

Creating test database for alias 'default'...
.......................................................................................................F....................EEE
======================================================================
ERROR: allauth.socialaccount.providers.openid.tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: allauth.socialaccount.providers.openid.tests
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/matt/django-allauth/allauth/socialaccount/providers/openid/tests.py", line 4, in <module>
    from unittest.mock import Mock, patch
ImportError: No module named mock


======================================================================
ERROR: allauth.socialaccount.providers.facebook.tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: allauth.socialaccount.providers.facebook.tests
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/matt/django-allauth/allauth/socialaccount/providers/facebook/tests.py", line 4, in <module>
    from unittest.mock import patch
ImportError: No module named mock


======================================================================
ERROR: allauth.socialaccount.providers.persona.tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: allauth.socialaccount.providers.persona.tests
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/matt/django-allauth/allauth/socialaccount/providers/persona/tests.py", line 4, in <module>
    from unittest.mock import patch
ImportError: No module named mock


======================================================================
FAIL: test_password_forgotten_url_protocol (allauth.account.tests.AccountTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matt/django-allauth/allauth/account/tests.py", line 189, in test_password_forgotten_url_protocol
    self.assertTemplateUsed(resp, 'account/password_reset_from_key.html')
  File "/home/matt/conf/venvs/allauth/local/lib/python2.7/site-packages/django/test/testcases.py", line 538, in assertTemplateUsed
    self.fail(msg_prefix + "No templates used to render the response")
AssertionError: No templates used to render the response

----------------------------------------------------------------------
Ran 127 tests in 12.967s

FAILED (failures=1, errors=3)
```

The errors are from not having mock installed and the failure I filed as #837.

### PR DESCRIPTION
**Pull request by yosemitebandit**
fixes #838

### CODE REVIEW

**Comment by JshWright** [comment]
I generally prefer requirements.txt to just be stuff you need to use the library in production. The vast majority of users have no reason to run the test suite, and therefore no need to clutter their environment.

Perhaps this would be better addressed as a section in the Readme.

**Comment by yosemitebandit** [comment]
But if I add this app to my Django system and I'm not already using mock, won't the all-encompassing `python manage.py test` fail?

**Comment by SteveByerly** [comment]
I would prefer not to have to install mock on my production servers as I will never use it there and it introduces a dependency i'd rather not have. I think it is reasonable to leave it out of the requirements.

**Comment by yosemitebandit** [comment]
What are your thoughts on adding a `requirements-dev.txt` or adding some note about setting up one's environment for testing or CI or contributing to the project?

Although I will certainly concede when the tests fail, their cause of failure is obvious (lack of mock).  And so if you think developers should be expected to figure that out, I can understand that sentiment.

**Comment by pennersr** [comment]
I would expect that on production you would be running from PyPI or using something this `pip install git+git://github.com/pennersr/django-allauth...`. So, whatever the contents of `requirements.txt`, production should be unharmed.

I don't expect many users are using `requirements.txt` at all. In fact, the file is Py2 specific (see comments in file). So, if we were to really clean things up, we would need both `-dev` and `-py2` vs `-py3` postfixes, which is a bit too much IMHO. So all in all I think I am okay with adding mock to the list and leave it at that ....

**Pull request merged**
