### PR TITLE
fix for coinbase api v2

### PR DESCRIPTION
**Pull request by jvilaikeo**
adjusted the coinbase v1 settings for v2. This will allow users on 1.11.6 and django-allauth 0.32+ to connect to coinbase.

This pull request is for issue:

https://github.com/pennersr/django-allauth/issues/1897

### CODE REVIEW

**Comment by pennersr** [comment]
This breaks the test suite...

**Comment by jvilaikeo** [comment]
How do i reinitiate the test suite?

**Comment by pennersr** [comment]
Test suite is automatically rerun after you update your PR. There are still issues...

**Comment by Igoranze** [comment]
Bump, this is still relevant. Any chance on merging to latest build?

**Comment by pennersr** [comment]
Last time I checked it broke the test suite. Currently, the branch has conflicts. These need to be cleared out first.

**Comment by Igoranze** [comment]
Made a new PR: https://github.com/pennersr/django-allauth/pull/3252

**Pull request closed without merging**
