### PR TITLE
support oidc groups scope

### PR DESCRIPTION
**Pull request by cyberb**
OpenID Connect supports groups scopes at least Authelia does, is it possible to populate that?

### CODE REVIEW

**Comment by pennersr** [comment]
Currently, `SCOPE` is picked up from the settings, like so:

```
    SOCIALACCOUNT_PROVIDERS = {
        "gitlab": {
            "SCOPE": ["api"],
            "APPS": [
                {
                    "client_id": "<insert-id>",
```

Though, for OIDC that is not a good fit, because if you have multiple different providiers they all start sharing the same scope. So we should move toward supporting:

```
    SOCIALACCOUNT_PROVIDERS = {
        "openid_connect": {
            "SCOPE": [... works but not a good fit ...],    # <-- CURRENT
            "APPS": [
                {
                    "provider_id": "authelia",
                    "name": "Authelia SSO",
                    "client_id": "<insert-id>",
                    "secret": "<insert-secret>",
                    "settings": {
                        "server_url": "https://auth.example.com/.well-known/openid-configuration",
                        "scope": [...NEW...],  # <-- NEW
                    }
                }
            ]
        }
    }
```

This can be done in: `allauth/socialaccount/providers/oauth2/provider.py::get_scope()`. I think adding support for that makes more sense than adding it as a default.

**Comment by cyberb** [comment]
oh I see, did not know about the current SCOPE part, it is actually ok for me as I am configuring paperless-ngx and I only have one provider.

What about extracting groups from the response, in adapter I do not seem to have access to the original response, only the result of a default extraction in data dictionary?

**Comment by pennersr** [comment]
> What about extracting groups from the response, in adapter I do not seem to have access to the original response, only the result of a default extraction in data dictionary?

Did you check the social account `.extra_data` field?

**Comment by cyberb** [comment]
Oh right this just worked
```
sociallogin.account.extra_data
```
Sorry feel free to close.

**Comment by aHVzY2g** [comment]
@cyberb sorry to ping you, were the groups directly available to you in `sociallogin.account.extra_data`, after adding the scope, or did you have to do anything else?

**Comment by cyberb** [comment]
I think just scope. it was done for paperless+authelia you can check here if you need more details:

https://github.com/paperless-ngx/paperless-ngx/compare/dev...cyberb:paperless-ngx:dev

https://github.com/syncloud/paperless/blob/master/cli/installer/openid_config.go#L42

https://github.com/syncloud/paperless/blob/master/config/paperless.conf#L97

**Pull request closed without merging**
