### PR TITLE
feat(accounts) - Delete account

### PR DESCRIPTION
**Pull request by 9mido**
Attempts to solve #2726, #344

Not sure how to do the adapter part where the django developer could override the forms and views for this. But otherwise, this is a minimal viable product & built in allauth way to allow users to delete their account. This code does delete the user and the developer could specify where to redirect after the account deletion with ACCOUNT_DELETE_REDIRECT_URL and whether they want to enable/disable account deletion with ACCOUNT_DELETE. 

The django developer should specify in their models with on_delete whether they want to delete things like media files from each account. The django developer should be able to customize the form and views from this new code so that they could do things like surveys or store feedback in the database to satisfy project specific needs. Otherwise something default like a checkbox for consent should be fine.

### CODE REVIEW

**Comment by ogurec-ogurec** [comment]
@9mido thanks, great job! Please tell me how you can issue a warning - that the page will be deleted permanently, for example (like when logging out)?

**Comment by 9mido** [comment]
@ogurec-ogurec Thanks. There are a couple of ways. You can override the new allauth delete.html template and add a <p> tag somewhere with your warning. The other way is to override the forms.py BooleanField label. And the page is not necessarily deleted permanently it is the entire account and possibly other data associated with that account will be deleted (but this depends on your app's models on_delete values if you want to delete everything or not). When the form submits after the user consents to having their account deleted, the user will be logged out automatically and their account will be deleted with or without extra data associated with it. Once deleted, the user that was deleted could always come back and re-create their account in the future.

**Comment by pennersr** [comment]
Closing for reasons mentioned here: https://github.com/pennersr/django-allauth/pull/2786#issuecomment-977960052

**Comment by aehlke** [comment]
I disagree with the logic, if I may: yes deletion requests can be improved, however it's now a regulatory requirement across the world enforced by various agencies as well as by Facebook themselves and other vendors, I think it's more important to satisfy the compliance requirement as a baseline and allow devs to extend or replace the behavior's business logic

**Pull request closed without merging**
