### PR TITLE
Add mailchimp OAuth2.

### PR DESCRIPTION
**Pull request by spool**
Hi, this is my first implementation. Passes tests on python 2.7 and 3.6 (I have added 3.6 to my local tox configuration, can add that commit) though I do get an odd error that seem unrelated:

```
ERROR: InvocationError: '/Users/griff/code/envs/insightsrit_prototype/src/allauth/.tox/py36-django17/bin/coverage run manage.py test allauth'
```

### CODE REVIEW

**Comment by pennersr** [comment]
Thanks... could you add mailchimp to the list of supported providers over at `overview.rst`, and to the list of installed apps in `test_settings.py` ?

**Comment by pennersr** [comment]
... and installation.rst

**Comment by spool** [comment]
Sorry for the delay, hadn't understood the isort errors initially. I also have a local commit to ``tox.ini`` to test python 3.6 (which is passes). Can add that as well.

**Comment by pennersr** [comment]
Please file a a PR for tox, thanks

**Comment by spool** [comment]
Sorry not sure what PR means? Do you mean commit that and ask for another Pull Request?

**Comment by spool** [comment]
Going to interpret it that way. Have committed change to my git repo. Will make pull request :)

**Pull request merged**
