### PR TITLE
fix(LINE): updated line api endpoint

### PR DESCRIPTION
**Pull request by hiimdoublej**
# Submitting Pull Requests
Made changes based on @thesarito 's previous submitted PR #2151 so that the tests should pass.

## General

 - [x] Make sure yo use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages). 
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [x] All Python code must be 100% pep8 and isort clean.
 - [x] Javascript code should adhere to [StandardJS](https://standardjs.com).
 - [x] If your changes are significant, please update `ChangeLog.rst`.
 - [x] Feel free to add yourself to `AUTHORS`.

### CODE REVIEW

**Comment by hiimdoublej** [comment]
@pennersr I see you applied a new tag `Needs improvement` on my PR, I'm glad to have receive your opinion on this PR, but could you elaborate on which part of my PR needs improvement ? Thanks.

**Comment by pennersr** [comment]
@hiimdoublej The branch cannot be merged as is --  "This branch has conflicts that must be resolved"

**Comment by hiimdoublej** [comment]
> @hiimdoublej The branch cannot be merged as is -- "This branch has conflicts that must be resolved"

Oh...OK, thought it was more than just that AUTHORS file conflict, maybe the coding style or anything I wasn't aware of. Will come up with a commit that solves the conflict.

**Comment by hiimdoublej** [comment]
@pennersr I thinks this PR is good to merge now ? Would you mind taking a look at this and, if no further concerns, merge this ? Thanks.

**Comment by pennersr** [comment]
@hiimdoublej  Thanks, but I am still seeing this:

image

**Comment by hiimdoublej** [comment]
Huh...Perhaps I should make another pull request with a up to date fork from this repo, my forked repo was from @thesarito since he was the one proposed the api endpoint change, I simply made the tests pass, but I guess I should refork from this repo, make the changes, then cite his changes somewhere. Thanks anyways.

**Pull request closed without merging**
