### PR TITLE
feat(login): deny unverified EmailAddress from login

### PR DESCRIPTION
**Pull request by iarp**
Allow admin to set a config option that disables a users ability to login via an unverified email address.

Only applies when there are multiple EmailAddress entries, single entries are handled by login system checking for verified emails when ``ACCOUNT_EMAIL_VERIFICATION = 'mandatory'``.

In relation to #650

## General

 - [x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [x] All Python code must be 100% pep8 and isort clean.
 - [ ] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [x] If your changes are significant, please update `ChangeLog.rst`.
 - [ ] Feel free to add yourself to `AUTHORS`.

### CODE REVIEW

**Comment by 9mido** [comment]
@iarp This is awesome! I hope this gets merged into the main branch soon after being in the backburner forever. 

Would you be able to help me make a PR for the 2 issues I recently solved on here via comments? I would like to make a custom timer setting for both of them but not sure how to prevent spamming of the re-send verification button and password reset emails.

**Comment by iarp** [comment]
``ACCOUNT_EMAIL_VERIFICATION`` has no direct affect on this code change. It's only used when ``ACCOUNT_AUTHENTICATION_METHOD`` is ``email`` or ``username_email`` as email is checked first in both cases. I did add a note in the configuration docs stating its recommended to set email verification to mandatory.

**Comment by stfenjobs** [comment]
+1
thank you

**Comment by pennersr** [comment]
I may be missing something, but if you have ACCOUNT_EMAIL_VERIFICATION set to mandatory, then what do you gain from another setting? With that setting configured as mandatory, you are already prevented from logging in if there is no verified email address. 

You can indeed have the case that one account has two email addresses attached, one verified, and one unverified. Currently, in that case, logging in with the unverified one will work as well, though I am not sure what the gain is in preventing that. The goal of verifying email addresses is that you want to make sure that the user is reachable, and to prevent the user from losing access to the account (e.g. in case he made a typ-o in his email address). That goal is met by the existing setting. What other goal is there?

**Comment by 9mido** [comment]
https://ux.stackexchange.com/questions/111005/what-is-the-point-of-email-verification

There are lots of reasons why a website should verify an email in that link. 

@ghost from issue 650 summarized one way how this could be abused. 

@pennersr I was able to login with an unverified email address after using the "Add email" feature with the "mandatory" setting. 

Steps to reproduce:

1. Sign up
2. Verify that email that just signed up
3. Login with that email you just signed up with
4. Add a new email for that account and do not verify it
5. Logout
6. Login with the new unverified email

Just seems like bad UX to me which could open up a can of worms as described in some of the problems that link above describes. 

Imagine if your website was a government one where there was all sorts of classified info. After using django-allauth and following the reproducible steps above, an unverified email address can login and gain access to all the classified info without proper verification. If a user adds an email that is not their own, the real owner of that email can gain access to that account with a password reset.

As for whether this should be a new setting or not, I don't really care if it is one or more than one setting as long as it gets fixed. If putting it under the existing setting, follow @iarp's logic and add it to that. Let's get it done.

**Comment by pennersr** [comment]
> https://ux.stackexchange.com/questions/111005/what-is-the-point-of-email-verification
> There are lots of reasons why a website should always verify an email in that link.

I am not questioning the merits of email verification. My point is, with the existing email verification setting set to "mandatory" you already have these points covered. You know you are dealing with a real person, you can contact that person, that person can recover his account should  he lose his password, and so on.
 
> @ghost from issue 650 summarized one way how this could be abused.

"Abuse" suggests there is a security issue at play, which there really is not. Also, #650 is wrong here:

    "But that only seems to prevent an unverified email from logging in when first creating an account"

With mandatory email verification, you cannot login into an account if that account does not have at least one verified email address.

Can you please sketch a scenario how this can be abused?

> @pennersr I was able to login with an unverified email address after using the "Add email" feature with the "mandatory" setting.
> 
> Steps to reproduce:

This is exactly what I mentioned in https://github.com/pennersr/django-allauth/pull/2627#issuecomment-704457534 -- you can indeed login using an unverified email address if and only if the account you are logging into has a verified email attached. 

I think the confusion mainly stems from a wording issue. If you say "was able to login with an unverified email address" that sounds alarming, and clearly wrong, but in reality, what you are doing, is logging into an account that does have a verified email address.

> Just seems like bad UX to me which could open up a can of worms as outlined in some of the problems that link above describes.

Can you please give specific examples of what we are trying to prevent?

> Imagine if your website was a government one where there was all sorts of top secret info. After using django-allauth and following the reproducible steps above, an unverified email address can login and gain access to all the top secret info without proper verification. 

This is not true. The user signed up for an account and verifies the email address, and added another 2nd unverified email address to his account. That same user can now login using both email addresses, and access his or her own data. A different user cannot login using that 2nd unverified email address, because he does not know the password to the account.  Again, the question is, what security issue is tackled by prohibiting the user from logging in using any of the two email addresses?

> If a user adds an email that is not their own, the real owner of that unverified email can receive that verification email, verify it or not, then gain access to that account with a password reset (since the verification email says which website it came from and will always send no matter how the email gets created - signup or add email), and steal that account owner's identity info stored on the site, hijack the account, delete the other verified emails, hold it as ransom, etc.

Isn't this handing over your keys to the burglar, and then complaining that you got robbed?

I don't see how verification would prevent this scenario. By adding the email address of the hacker to your own account you are effectively allowing that email address to login, provided, of course, the hacker knows the password. The improvement point in this scenario is not sending out password reset emails to unverified emails and requiring the user to login before marking an email address as verified (*).
 
> As for whether this should be a new setting or not, I don't really care if it is one or more than one setting as long as it gets fixed. If putting it under the existing setting, follow @iarp's logic and add it to that. Let's get it done.

Don't get me wrong -- I am all for fixing things and getting things done, but I would really like to know what the thing is that needs to get fixed/done.  So far, I see (*) -- yet this ticket is about email verification during login?

**Comment by 9mido** [comment]
@pennersr 

I am using the latest allauth version on PyPi.

How is it covered? In the steps below, b@gmail.com who is unverified can log in. b@gmail.com bypasses the mandatory setting for itself. 

1) Sign up with a@gmail.com

2) Verify a@gmail.com

3) Log in as a@gmail.com

4) Add to that same a@gmail.com account, b@gmail.com

5) Do not verify b@gmail.com

6) Logout of a@gmail.com

7) You can now login as a@gmail.com (verified) or b@gmail.com (unverified) as long as you know the password. 

Are you aware of how Netflix users like to share accounts with their friends so only one user buys and the rest of the users leech off of the buyer? This is a very common use case where you have no idea how your users will behave on your website. This is similar to Netflix but with allauth, a user could have more than one email address. This can overcomplicate matters compared to Netflix with just one shared email among users.  

Let's say I want to sign up for a website that uses allauth. Then I discover oh wow someone else is already signed up (or added later) my own personal email address that I did not sign up (or added) myself. Might as well reset the password for that user who has my email address already added because screw them for adding my own personal email address without my permission. Then I reset the password using my own personal email address that somebody else already added (either from a typo or just them adding my own personal email address for the hell of it). Great now I gained access to that other person's account who signed up with my email address. Wow I could see all their credit card info, address, name, everything I want to know about this person who added my email! This makes my job as a social engineer easier I could take this info about this person and totally ruin their life by accessing their other online accounts. To punish them some more, I will cause a denial of service where I verify my email address that was previously unverified by them, make my email the primary one, and remove their email address and prevent them from logging in again - causing a lock out of the original signed up user. Soon after I receive a customer support ticket from the original owner I cannot access my account. I say to them oops you shouldn't have added another person's email address that was not your own! How is this not a security issue and how could it not be abused if someone just randomly adds as many email addresses to their account as they wanted even if they were not their own and those other people can do these steps and access the original account owner's account? 

Steps (continued from above) outlining this:

8) as b@gmail.com go to the website that sent the verification email and click "forgot password"

9) Change the password that is also connected to a@gmail.com so only b@gmail.com can access it

10) Login as b@gmail.com

11) Verify yourself as b@gmail.com

12) As b@gmail.com, delete a@gmail.com

Outcome: a@gmail.com cannot login and their password was changed thanks to b@gmail.com's actions. 

Sure it gives the burglar the key but that is a big enough key to ruin someone's life/hurt someone over something as simple as mistyping your commonly named email address that a lot of other people might use. Think Michael vs Micheal or Bryan vs Brian as the email address typo. 

Video proof: 

https://streamable.com/llb1ak

If you cannot view the video, use a proxy or VPN if your country blocks it. 

Sketch:

https://imgur.com/a/iWZE4mN

Signing up for a website using another person's email address happens all the time. Lookup on Google "someone signed up using my email on another website". The results are staggering how often it occurs. 

Why would I want to have any unverified emails at all? If I were a marketer sending emails, I wouldn't want to waste time sending marketing emails to unverified emails that are not legitimate and bounce. Sure I could run a SQL query to filter unverified emails out, but why design it that way? If your email provider has email sending limitations, those unverified emails that are sent marketing material prevents me from sending more emails to legit people because I already hit my daily sending limit by wasting time/resources on the unverified ones. In those cases, I am not dealing with a real person and I have to take lots of time figuring out who the original verified owner of that account is who has multiple emails added on their one account. Even worse, if these unverified emails are actually owned by someone else, they will receive tons of spam from my website's marketing emails without ever opting into marketing emails. CAN-SPAM laws come into play and that is a lawsuit waiting to happen as it will be difficult for these unverified people to opt out of marketing emails unless they contact my website customer support or there is a mechanism on the website to deal with opting themselves out that they can access. 

The main benefit to verifying these added e-mails is to try to prevent these situations from accidentally happening.

Isn't the whole point of having a setting so that the site administrator could have their site work any way they wanted? If you want to keep the behavior you describe then fine, keep your setting as ACCOUNT_LOGIN_VERIFIED_ONLY=False. As for me and many of the other great people who contributed to the issues/PR section and originally raised a red flag surrounding this and the other core issues, we are most likely going to want to use ACCOUNT_LOGIN_VERIFIED_ONLY=True. Each user has their own use case and that is fine. Give them the freedom to do what they want. 

@iarp's PR's with settings are all connected in one way or another solving quite a few core allauth issues that have been around a while. What do you/we have to lose by not trying them out? Just configure the settings to how you want them if you don't like them. Why combine settings into previous ones? This relates back to the security principal called "separation of duties" but for settings. I believe one setting should do one thing and do it well. If combining into already existing settings, those settings would become bloated with all sorts of extra stuff and might make things more confusing for future development efforts.  

Hopefully I clarified things and it makes sense.

**Comment by pennersr** [comment]
> In the steps below, [b@gmail.com](mailto:b@gmail.com) who is unverified can log in. [b@gmail.com](mailto:b@gmail.com) bypasses the mandatory setting for itself.
>
>     1. Sign up with [a@gmail.com](mailto:a@gmail.com)
>     2. Verify [a@gmail.com](mailto:a@gmail.com)
>     3. Log in as [a@gmail.com](mailto:a@gmail.com)
>     4. Add to that same [a@gmail.com](mailto:a@gmail.com) account, [b@gmail.com](mailto:b@gmail.com)
>     5. Do not verify [b@gmail.com](mailto:b@gmail.com)
>     6. Logout of [a@gmail.com](mailto:a@gmail.com)
>     7. You can now login as [a@gmail.com](mailto:a@gmail.com) (verified) or [b@gmail.com](mailto:b@gmail.com) (unverified) as long as you know the password.


You are repeating the same scenario as your steps 1-6 from https://github.com/pennersr/django-allauth/pull/2627#issuecomment-704607058 which is the same scenario I was referring to in https://github.com/pennersr/django-allauth/pull/2627#issuecomment-704607058.

Please explain how preventing the unverified b@gmail.com from logging in would address this scenario. Suppose we merge this PR, and indeed b@gmail.com is prevented from logging in. What is stopping anybody from simply clicking the verification email sent to b@gmail.com as part of your step 4?

With, or without the changes in this PR, b@gmail.com will be able to login. Don't you agree?

That is why I mentioned that you would need prevent marking an email addres as verified without re-authenticating (e.g. re-entering your password). This way, if for unexplained reasons, I would add hacker@gmail.com to my account, hacker@gmail.com will not be able to complete the verification cycle because that person does not have my password. To prevent hacker@gmail.com from obtaining the password, you would also need to stop the unverified hacker@gmail.com from receiving password reset mails.

Only with these two changes (re-authenticate before verifying, password reset for verified mails only), hacker@gmail.com won't be able to login. The changes made in this pull request would not prevent the login by hacker@gmail.com at all.

> Let's say I want to sign up for a website that uses allauth. Then I discover oh wow someone else is already signed up (or added later) my own personal email address that I did not sign up (or added) myself. Might as well reset the password for that user who has my email address already added because screw them for adding my own personal email address without my permission.

Okay, in this case you are the hacker. So, someone signed up and added your email address. Therefore, you have a confirmation email in your inbox that you can click, making your email a verified one. Again, this pull request does not solve the scenario you are sketching.

> Why would I want to have any unverified emails at all?

It is a fact you lose a percentage of users in your signup funnel if you require verification. Therefore, allauth tries to be project agnostic and it is left up to the project to make a choice whether or not verification is set to mandatory.

> @iarp's PR's with settings are all connected in one way or another solving quite a few core allauth issues that have been around a while. What do you/we have to lose by not trying them out?

IMHO you do not solve security issues by trying things out, you would gain a false sense of security by doing so. As indicated above, I could simply merge this PR, yet, your whole scenario would still remain unaddressed.

**Comment by 9mido** [comment]
I repeat myself again to make it easier to follow along with an example showing a@gmail.com and b@gmail.com trying to clarify myself from the previous comment, or give you and others a way to test it yourself the same exact way I did. 

I disagree in one area where it would have helped. In the video, I was able to perform a password reset as b@gmail.com while b@gmail.com was still unverified to access a@gmail.com's account after the reset. Then after I access a@gmail.com's account as b@gmail.com then I go and verify as b@gmail.com and then delete a@gmail.com's account and take over the entire account and lock out a@gmail.com. 

If this PR was merged, we would have been able to stop the unverified b@gmail.com from logging into a@gmail.com's account after the password reset. 

Now, if b@gmail.com verifies then performs the password reset, they would then be able to login anyways and a@gmail.com would still be compromised if b@gmail.com was another person a@gmail.com did not know about. So in that area I agree.

But that is where the other PR's @iarp made come in and how they are somewhat related to one another. That is why I recommend a MAX_EMAIL_LIMIT of 1 from the other setting to prevent anyone unknown from accidentally adding another person's email address from a typo and preventing such situations from happening. Worst case scenario is if the user cannot access their account with MAX_EMAIL_LIMIT of 1, they can contact customer support and perform a password reset or change the email in the database as long as they answer questions about themselves truthfully. 

Re-authenticate before verifying & password reset for verified mails only (https://github.com/pennersr/django-allauth/issues/2360) - Ok these are not bad ideas and I support them. I recommend you sticky them to the top of the allauth github issues/main page to direct people's attention that it is a higher priority item so that it gets done sooner. 

Why not implement these ideas you just mentioned and still merge this PR anyways? It will have another layer of protection then just in case. 

If not then fine don't merge this PR if the other ideas you mentioned become PRs and work well enough. I will be sure to test it and let you know if there is a problem.

**Comment by pennersr** [comment]
Closed via e97a6669 -- to reiterate, this commit does not fix a security issue -- it merely results in a more consistent interpretation of mandatory email verification.

**Comment by 9mido** [comment]
@pennersr I just tried testing your commit you wrote and it does not seem to work the way it is described in the changelog merge link unless I am doing something wrong. 

I did:

pip3 install git+https://github.com/pennersr/django-allauth

Then I ran through the same exact steps as I did in the video and as written above. 

I can still login with the unverified email account attached to the verified one. 

I am a bit confused. Just to be clear, you say in the comment above this commit does not fix a security issue but the wording in the changelog says "If email verification is set to mandatory, the email address you use to login with must now be verified as well". Was this commit not meant to alleviate the steps I tried performing above? It sounds like the changelog wording does fix it though? 

Should I make a new issue for the "Re-authenticate before verifying & password reset for verified mails only" features to handle the scenario I outlined above since the problem I brought up still exists?

**Comment by iarp** [comment]
[The view](https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L776) has no logic (assuming you have `ACCOUNT_LOGIN_ON_PASSWORD_RESET=True`). From what I can see it has no idea which email address the reset link was clicked from since the reset url seems to be solely based on a [token made from the user object and the users pk](https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L538).

**Comment by pennersr** [comment]
@9mido That wording is chosen intentionally, because this is not a case where a security breach is fixed. The scenario starts out from an insecure context. An email address is the key to your account. If you add other people's email addresses to your account, or vice versa, then that is asking for trouble. 

I am not sure yet on how to proceed further here. For example, not sending password reset mails can have the side effect that people are locked out of their account:

1) Person A signs up for an account, adds email A and B
2) Person B does not confirm the email address, the email address B remains unverified
3) Some time later, person B wants to make use of the web site as well, but finds he is unable to signup nor able to reset his password.

So, in this scenario person A effectively prevents person B from signing up (provided, password reset mails are not sent to B because it is unverified).

Also, so far, the discussion is on having an account with two emails attached from 2 different people. What if it has one email, and one social account?

All in all, I think it would be best to come up with concrete proposals and reason on those first before taking a next step.

**Comment by 9mido** [comment]
@pennersr 

All good points, and I agree. I do not use any social features of allauth for anything so my understanding of it might be blurry and I might not be the best person to solve that particular aspect of this problem.

For point 3, is this after another PR is made regarding the additional authentication for password reset? And some time later does that mean before or after ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS? 

When you say one email and one social account does that mean one email for person A and one social account for person A? One email for person A and one social account for person B? Both?

I was not sure how exactly to test your commit to see what change occurred. What do I have to do to test it? Or is it like @iarp said and I cannot necessarily test your commit the same way like the video/sketch? Sorry I am not as advanced as you guys when it comes to writing/reading/understanding allauth's code. 

Just brainstorming here but I am thinking due to the social aspect there would need to be a way to link the person to that social account to see if they truly owned that social app and the allauth account? Or I am thinking more along the lines of stuff only the real person would know (like what kinds of activities related to allauth the person knows they did - last changed password, last login date, past email addresses used, original signup date, etc). To me original signup date is better out of this group and every user should have a date they could refer back to in their email when they first signed up (unless they delete that signup verification email or remember the month/day/year from memory). 

What if you forced username field in addition to email field for signups whenever someone wishes to use a social account. So instead of needing to know just the email as the key to the account (where person B could own that email), username could be used as a secondary key where only person A knows what their username is? Person B probably would not know the username of the account. However, I realize not all people who use allauth would want to use usernames and email fields for signups to be forced upon them and it might not be the best way forward since users might forget their usernames also.

Maybe something like a webhook to/from the social API to communicate with allauth? Like a notification code verification like you would receive via SMS when you want to do something? To me this seems hard to do though and there are a ton of social apps allauth uses (so it would most likely be something common between all of them) but you all are the experts on this social app stuff not me. 

Otherwise I am not sure at this time either. This is indeed a tough problem to solve. You just threw a curveball at me with this social app stuff lol. Depends on how you answer the clarification questions but I tried brainstorming here to work with whatever answer you provide.

**Pull request closed without merging**
