### PR TITLE
chore(mfa): make qrcode an optional dependency

### PR DESCRIPTION
**Pull request by akx**
## Why?

Users may wish to use an alternative QR code implementation such as https://pypi.org/project/segno/, or generate QR codes from TOTP URLs client-side, and don't need the extra dependencies.

## General

 - [x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [x] If your changes are significant, please update `ChangeLog.rst`.

### CODE REVIEW

**Comment by pennersr** [comment]
This is a backwards incompatible change that breaks existing installations silently. 

How about we move that `build_totp_svg` into the MFA adapter instead? Then, just don't install allauth using the `[mfa]` extra and you are free to plugin your own rendering engine, *without* breaking backwards compatibility.

**Comment by pennersr** [comment]
> There's precedent for this sort of thing...

True, and that one caused a lot of issues as well. There were a lot of complaints and bugs reported about installs where Google wouldn't work anymore because `[socialaccount]` was now all of a sudden needed (e.g. https://stackoverflow.com/questions/78453278/i-have-used-to-google-provider-in-social-auth-in-django-but-provider-is-not-sho).  Though, that  was about transitioning from always "installing the world" to at least install only what's needed depending on what `allauth.<subapp>` you are using -- that does add value. I do not think that it is worth breaking backwards compatibility over the `qrcode` package.

> That feels a bit unfortunate too. What if MFA functionality gets new actually mandatory deps later? Then you'd have installations that are not using the extra, and they'll break in an interesting way too.

But here, we would be breaking installations for people who consciously decided to deviate from standard allauth by not installing `[mfa]` and thereby willingly taking on the consequences of that choice. That is far less an issue (if one at all) compared to breaking installations for people who just follow the regular installation guides.

**Comment by akx** [comment]
> There were a lot of complaints and bugs reported about installs where Google wouldn't work anymore [...]

Which is why we read changelogs when upgrading and docs when setting things up... 😅 

>  But here, we would be breaking installations for people who consciously decided to deviate from standard allauth by not installing `[mfa]`

But I'd _want to_ have the `[mfa]` extra for future-proofing... 😄

What if I added an early check in `allauth.mfa.views` for `qrcode` being installed? IOW, if you've hooked up the MFA frontend, it'd remind you to install `qrcode` if it's otherwise not installed?

**Comment by akx** [comment]
Moving `qrcode` to a late import (like in this PR) + adding a (currently empty) extra `[mfa-min]` (and documenting it) sounds like a good deal to me?

**Comment by mecampbellsoup** [comment]
Is Segno somehow preferable to qrcode?

**Comment by mecampbellsoup** [comment]
> Hmm. As it is, `build_totp_svg` is only used by the MFA view (and as such is only a dependency for headed installations) – the adapter doesn't feel like the right place for it...

Just a heads up/possibly related... in [this recent PR I opened](https://github.com/pennersr/django-allauth/pull/3884), I added `totp_url` attribute to the headless MFA activate endpoint's response data. Maybe we should also include/add `totp_svg`...

**Comment by pennersr** [comment]
Soon, MFA will support webauthn, and for that another dependency is needed: `fido2`. Options:

- `pip install django-allauth[mfa,webauthn]`
- Just `pip install django-allauth[mfa]`, and use `mfa-min` for a version without `webauthn`.

The trouble with micro managing the dependencies is that the test suite would need to cover various combinations. So it is TBD what is the best approach here, just have 2 MFA flavors: minimal, without webauthn and qrcode and regular including all, or ...

**Comment by pennersr** [comment]
One of the issues is that `mfa-min` would not depend on anything.

> What if MFA functionality gets new actually mandatory deps later?

So where do you see `webauthn` in this picture? Is that something part of both `mfa` and `mfa-min`?

**Comment by pennersr** [comment]
I must admit, I am leaning towards not picking this up. Rationale:

- Micromanaging dependencies would almost result in a 1:1 mapping of an `[extra]` matching some `pip install extra`. That does not make sense, because the only benefit would be a version pin, but other than that there is almost no difference with not installing `[mfa]` and cherry picking the dependencies yourself.

- Somehow grouping dependencies into bigger pieces is quite arbitrary. E.g. where does `[webauthn]` reside, likely not in `[min]`, but what if people don't need `[webauthn]`. 

All in all, this way working...

> How about we move that build_totp_svg into the MFA adapter instead? Then, just don't install allauth using the [mfa] extra and you are free to plugin your own rendering engine, without breaking backwards compatibility.

... is starting to look quite attractive.

> As it is, build_totp_svg is only used by the MFA view (and as such is only a dependency for headed installations) 

Currently, that is true, but it is not too far fetched for a mobile client to want to render an SVG as well.

**Comment by akx** [comment]
> Is Segno somehow preferable to qrcode?

Zero dependency, more featureful (IMO) and actively maintained (c.f. https://github.com/lincolnloop/python-qrcode/commits/main/). I'm sure [my PRs to `qrcode` will get looked at any moment now!](https://github.com/lincolnloop/python-qrcode/pulls/akx) 😁 

> So where do you see `webauthn` in this picture? Is that something part of both `mfa` and `mfa-min`?

My favorite (which would imply changing what the `mfa` extra currently does) is

* `mfa`: MFA core – bring your own QR codes, no support for Webauthn
* `mfa` + `qrcode`: MFA with QR code generation support via `qrcode`, no support for Webauthn
* `mfa` + `qrcode` + `webauthn`: MFA with QR code generation support via `qrcode`, Webauthn supported

(and of course `mfa` + `webauthn` if someone needs that combo).

I would appreciate the `fido2` dependency ending up in its own extra in any case.

> The trouble with micro managing the dependencies is that the test suite would need to cover various combinations.

I'm not sure that's 100% necessary, so long as the scope of the optional dependencies is kept atomic, and e.g. late imports have comments near them noting that this is an optional dep, so if anyone was about to hoist them to top-level, they'd, well, not do that.

> Currently, that is true, but it is not too far fetched for a mobile client to want to render an SVG as well.

Speaking of which, a PNG actually sounds more attractive for a mobile client (e.g. React Native doesn't have, pardon the pun, native SVG support as far as I know).

**Comment by pennersr** [comment]
> My favorite (which would imply changing what the mfa extra currently does) is

That would result in a 1:1 mapping from one extra to one package:
- `[mfa]`: MFA core has no dependencies -- so no `pip install`.
- `[qrcode]`: Is identical to `pip install qrcode`.
- `[webauthn]`: Is identical to `pip install fido2`.

So, I really don't see the benefit of doing that, as the end result is the same as not installing `[mfa]` and cherry picking the dependencies your self:

- `pip install django-allauth[mfa,qrcode]` is identical to `pip install django-allauth qrcode`. 
- `pip install django-allauth[mfa,webauthn]` is identical to `pip install django-allauth fido2`.

Sure, somewhere it needs to be documented that you need `fido2` for Passkey support, but that holds for `[webauthn]` as well. 

So there is no real benefit, and at the same time it breaks backwards compatibility. 

> PNG actually sounds more attractive for a mobile client

While RN doesn't have SVG support out of the box, there is a well maintained React Native SVG package out there that I have successfully used in the past.

Summarizing:
- Altering the `[extras]` is not going to fly.
- What is an option is to replace the use of `qrcode` with `segno`.
- And what's also worthwhile pursuing is moving the `build_totp_svg()` logic into the MFA adapter.

**Comment by pennersr** [comment]
Closed via 18c7ca47

**Comment by akx** [comment]
I'm fine with this resolution 😄 

Thanks for the discussion, and as always, thank you for the library and the effort you've put into it!

**Pull request closed without merging**
