### PR TITLE
docs: use staff_member_required to protect admin

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/pennersr/django-allauth/issues/1789.
Ref: https://stackoverflow.com/a/45328687/15690

### CODE REVIEW

**Comment by pennersr** [comment]
`staff_member_required` does not use the allauth login (and its brute force protection as documented in the paragraphs about your changes).

**Comment by blueyed** [comment]
@pennersr 
Please re-check: regarding brute-force it is the other way around.  `login_required` will display the login form (for brute forcing).
And `login_url` is used to redirect through allauth.  That should be clarified probably, i.e. that `settings.LOGIN_URL` should be set to allauth's.

**Comment by pennersr** [comment]
If you look here...

https://github.com/django/django/blob/b9cf764be62e77b4777b3a75ec256f6209a57671/django/contrib/admin/views/decorators.py

... you'll see that it does not use the regular login_required decorator, and redirects to `admin:login`. As a result, the issue warned about in the documentation is not tackled.

**Comment by blueyed** [comment]
`login_url='admin:login'` is the default - this PR uses `settings.LOGIN_URL` there, i.e. allauth.
It checks if it is a staff user, which AnonymousUser is not.. ;)

**Comment by blueyed** [comment]
(I have a test for this actually, so it is working as expected really)

**Comment by blueyed** [comment]
Can we have this then, please? :)

**Comment by 9mido** [comment]
This seems similar to this:

https://github.com/pennersr/django-allauth/commit/90a2eb917d435c40f70867632994e4e35d8ac784

**Pull request merged**
