### PR TITLE
Update Travis CI matrix

### PR DESCRIPTION
**Pull request by kevin-brown**
- [x] Reorganize matrix to make it more clear what combinations are running
- [x] Test on Python 3.7

### CODE REVIEW

**Comment by kevin-brown** [comment]
The Flake8 build is failing now because it is actually running Flake8 on the files. Before it appeared to be skipping all of them, which allowed for some bad import sorting to occur.

Old: https://travis-ci.org/pennersr/django-allauth/jobs/505191282
New: https://travis-ci.org/pennersr/django-allauth/jobs/505194883

I'm going to tackle this in a separate pull request next time I get around to it.

**Comment by pennersr** [comment]
This branch has conflicts.

**Comment by blueyed** [comment]
@kevin-brown 
Do you plan to update it?

**Comment by kevin-brown** [comment]
To be honest, this one went to the back of the queue. It's still in the queue, just not at the top so I haven't gotten to it yet.

I'll get around to rebasing the latest changes.

**Comment by pennersr** [comment]
This is outdated with the recent changes of moving to Django 3 and dropping Python 2.

**Pull request closed without merging**
