### PR TITLE
Settings for checking outdated data when authorizing via telegram.

### PR DESCRIPTION
**Pull request by Graphanton**
Added the ability to set the period for checking outdated data when authorizing via telegram.

### CODE REVIEW

**Comment by pennersr** [comment]
> If the time of the telegram server differs from the time of your server...

Wouldn't it be better in this case to actually fix the root cause and make sure your server is running NTP so that the time is not out of sync?

**Comment by Graphanton** [comment]
Yes. I removed it myself. But since Telegram does not strictly regulate the authorization expiration time, I can set my own expiration time, which can be less than the default.

**Comment by pennersr** [comment]
I am okay with adding this functionality, though I think it would be good to reword the documentation. Because "If the time of the telegram server differs from the time of your server..." you need NTP and not this change.

**Comment by pennersr** [comment]
Thanks for rewording. One last thing, the code is not black formatted causing the build to fail. Can you look into that?

**Comment by Graphanton** [comment]
> 

Ready!

**Pull request merged**
