### PR TITLE
Update socialaccount.py to resolve Key Error

### PR DESCRIPTION
**Pull request by nscozzaro**
Resolves issue in https://github.com/pennersr/django-allauth/issues/1473#issuecomment-508933251

# Submitting Pull Requests

## General

 - [ ] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [ ] All Python code must be 100% pep8 and isort clean.
 - [ ] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [ ] If your changes are significant, please update `ChangeLog.rst`.
 - [ ] Feel free to add yourself to `AUTHORS`.
 
 ## Provider Specifics
 
 In case you add a new provider:
 
- [ ] Make sure unit tests are available.
- [ ] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [ ] Add documentation to `docs/providers.rst`.
- [ ] Add an entry to the list of supported providers over at `docs/overview.rst`.

### CODE REVIEW

**Comment by cdvv7788** [comment]
> Alternatively this can be changed to:
> 
> ```
> request = context.get('request')
> if not request:
>     request = context.request
> ```

Or shorter

request = context.get('request', getattr(context, 'request'))

I prefer the try/except tho. It makes the issue more explicit.

**Comment by cdvv7788** [comment]
In the tests, the following issue is happening:
`'Context' object has no attribute 'request' is showing up`
@nscozzaro when can that happen? (check travis).

**Comment by LennyLip** [comment]
> In the tests, the following issue is happening:
> `'Context' object has no attribute 'request' is showing up`
> @nscozzaro when can that happen? (check travis).

```
request = context.get('request') # context dict has no 'request' key (initial issue)
if not request:
    request = context.request # context it's not [RequestContext](https://docs.djangoproject.com/en/2.2/ref/templates/api/#django.template.RequestContext) object
```

**Comment by LennyLip** [comment]
it seems issue with a new test from Will Gordon ( https://github.com/pennersr/django-allauth/commit/d34018a4ef40eb0c112c82672abeef402af7ee98#diff-d3cde51e61b93ed33c6c6bab2adfa4e0R72 ). 

RequestFactory is not proccessed 'django.template.context_processors.request' by default.

> The RequestFactory shares the same API as the test client. However, instead of behaving like a browser, the RequestFactory provides a way to generate a request instance that can be used as the first argument to any view. This means you can test a view function the same way as you would test any other function – as a black box, with exactly known inputs, testing for specific outputs.

https://docs.djangoproject.com/en/2.2/topics/testing/advanced/#django.test.RequestFactory

**Comment by nscozzaro** [comment]
@LennyLip, should that test be changed? What change would you propose?

**Comment by LennyLip** [comment]
I think we need to add 'request' context via

```
   engine = DjangoTemplates({
            'DIRS': [],
            'APP_DIRS': False,
            'NAME': 'django',
            'OPTIONS': {
                'context_processors': ['django.template.context_processors.request',],
            },
        })
```

while running this test, like an in:

https://github.com/django/django/blob/master/tests/template_backends/test_django.py#L17

**Comment by nscozzaro** [comment]
@LennyLip, sounds like you've identified the issue, maybe open a pull request for that test?

**Comment by pennersr** [comment]
See https://github.com/pennersr/django-allauth/issues/1473#issuecomment-249037636 -- I am closing this as it is not clear what this PR is fixing.

**Pull request closed without merging**
