### PR TITLE
Add ACCOUNT_SIGNUP_ADD_MESSAGE option

### PR DESCRIPTION
**Pull request by jonashaag**
Use case: Hide the "confirmation email sent" message **only directly after signing up** (if optional email verification)

### CODE REVIEW

**Comment by jonashaag** [comment]
I surrender. No idea how flake8 expects me to indent that line here.

Rest of the tests pass.

**Comment by jonashaag** [comment]
Hi @pennersr, any feedback on this?

**Comment by pennersr** [comment]
There is no need to introduce additional settings for this. If you override the default email_confirmation_sent.txt template with a blank one, this automatically disables that message. I prefer this above introducing another setting.

**Comment by jonashaag** [comment]
No, this also disables the message when using the "re-send confirmation message" feature.

**Comment by jonashaag** [comment]
@pennersr bump

**Comment by jonashaag** [comment]
@pennersr Can I get some feedback on this?

**Comment by pennersr** [comment]
Adding a one off setting for just this specific message introduces inconsistency, you would expect a similar setting for the other messages as well. Instead, opted for adding more context to the template so that you can decide inside the template how you want to handle this. See: fc772f29

**Pull request closed without merging**
