### PR TITLE
adding the trello integration

### PR DESCRIPTION
**Pull request by agudpp**
hi pennersr, here we implemented the integration with trello.

salu

### CODE REVIEW

**Comment by pennersr** [comment]
Thanks... can you add the provider to test_settings, overview.rst, installation.rst, and if you like, feel free to add yourself to AUTHORS.txt

**Comment by agudpp** [comment]
sure no problem, done :), let me know if looks good

**Comment by pennersr** [comment]
Thanks... the build is failing due to issues in the import order, can you fix them (or run make isort-fix) ?

**Comment by agudpp** [comment]
hi @pennersr, just see this, i think it is better if i use one automatic formatter for those errors.
what do u use or should I use?

thanks

**Comment by pennersr** [comment]
`isort`... just run `make isort-fix` and it will reformat.

**Comment by agudpp** [comment]
hi @pennersr, just saw this, seems that `make isort-fix` is not enough... or using different version / configuration for it..
what should i do? there is a way to compile locally exactly as travis is doing it?

salu

**Comment by pennersr** [comment]
isort did fix things, but next to clean imports we also have pep8 running to keep the code clean.

You can check the output in the travis build log:

```
flake8 --exclude=migrations allauth

allauth/socialaccount/providers/trello/provider.py:34:1: E305 expected 2 blank lines after class or function definition, found 1

allauth/socialaccount/providers/trello/views.py:19:5: E303 too many blank lines (2)
```

These need to be resolved manually...

**Comment by pennersr** [comment]
Thanks!

**Comment by agudpp** [comment]
thanks to you for the help 👍

**Pull request merged**
