### PR TITLE
Allow simple e-mail replacement when MAX_EMAIL_ADDRESSES=1

### PR DESCRIPTION
**Pull request by pktiuk**
Closes: https://github.com/pennersr/django-allauth/issues/3062

This is just a draft to show general idea.   
But I am not whether is there any chance of getting a review and merging it, because there are a lot of PR-s without any review or comment from maintainers. Is this repo actively maintained? (If yes, I will finish this code and change from draft to proper PR)

I think this code would be very useful in cases when we expect from users having one email.  
In general this case complicates process of changing email, because you can't add a new one and remove old one, nor remove old one to add a new one (when users have to have emails linked with accounts).

## General

 - [x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [x] All Python code must formatted using Black, and clean from pep8 and isort issues.
 - [x] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [x] If your changes are significant, please update `ChangeLog.rst`.
 - [x] If your change is substantial, feel free to add yourself to `AUTHORS`.
 
 ## Other things to do

- [ ] Fix tests
- [ ] Add migration
- [ ] Test it manually with my app

### CODE REVIEW

**Comment by e2489** [comment]
Why is there not more attention being paid to this issue? Being able to have one email address that users can change seems like extremely basic functionality. Almost every site on the internet does it this way. The way it's handled now is very outdated and overly complicated.

**Comment by pktiuk** [comment]
> Is this repo actively maintained?   

It seems to be either not actively maintained, or just not open for contributors from outside.   
That's a shame.

**Comment by pennersr** [comment]
This is a draft PR which is a bit short on details. It suggests a new "replace" email operation but does not explain how that would work. Particularly, in order to allow users to change their email you need to let them input a new email address, verify that one, and only once verified you can drop the old one. If you do not follow these steps users can and will lock themselves out of their account by inputting an email address with a typ-o. How would this new "replace" operation tackle this scenario?

**Comment by pktiuk** [comment]
I was just unsure whether anyone would look at this PR and whether there is any need for this feature, and I wanted to check it with this basic PR. (I did not get any feedback in the linked issue, and I was not sure about that)  

> How would this new "replace" operation tackle this scenario?  

I think I will just create a simple form class validating everything.  

I will soon update this PR with a more detailed implementation.

**Comment by pennersr** [comment]
But this goes beyond form validation, as you would need to store the new address, wait for it to be validated and only then you could swap. Perhaps, before starting to implement it, you could sketch how you are going to tackle it? It's difficult to judge whether a feature can be merged if it is not clear how the scenario is going to look like...

**Comment by pktiuk** [comment]
> If you do not follow these steps users can and will lock themselves out of their account by inputting an email address with a typ-o.

I think the form should contain two fields with email fields to avoid simple mistakes like typos.

> But this goes beyond form validation, as you would need to store the new address

This is the case only when email verification is mandatory. In the case of optional email validation, we can just swap emails.

For the case of mandatory validation I think the best solution would be just adding the second, unconfirmed email assigned to user (I think model `EmailAddress` should get a flag called `replacement`) and sending a confirmation email.  

Only after clicking confirmation link we could delete the old email and mark the new one as validated.

**Comment by e2489** [comment]
I'm new to django-allauth, so forgive me if this makes no sense or isn't plausible, but why not just add an actual 'change email' feature, separate from adding/removing addresses?

Something like an ACCOUNT_CHANGE_EMAIL configuration option, which requires ACCOUNT_MAX_EMAIL_ADDRESSES=1. If this is enabled, add/remove email becomes 'change email'. Store the pending email address, and once verified, replace the old one. If there's a typo or they try to change it again before verifying (for whatever reason), just invalidate the initial request and start over.

**Comment by pktiuk** [comment]
@pennersr   
What do you think?  
I had some time and wrote some code showing what I want to do.

@e2489  
I think it is a question to repo maintainer.   
I will comply with any decision they will make.

**Comment by pktiuk** [comment]
@pennersr

**Comment by e2489** [comment]
Yeah, really hoping we can get this incorporated. It would be very useful.

**Comment by pennersr** [comment]
Wondering, do we really need a `replacement` flag? Can't this information be derived from the fact that the max. number of email addresses is 1, yet, a second one is added and verified, implying the first one should get replaced?

**Comment by pktiuk** [comment]
@pennersr   
You are right.  
When I started coding this I was not sure.

I removed `replacement` flag.

**Comment by pktiuk** [comment]
@pennersr

**Comment by pennersr** [comment]
Closing in favor of #3346

**Pull request closed without merging**
