### PR TITLE
Update allauth to utilize url namespaces.

### PR DESCRIPTION
**Pull request by wldcordeiro**
Allauth was using urls like `account_signup` and this seemed to be antiquated with the existence of namespaces. I updated it to utilize namespaces. The entire test-suite is now passing.

### CODE REVIEW

**Comment by JshWright** [comment]
Wouldn't this be a breaking change for folks who have references to those URLs in their existing code?

**Comment by SteveByerly** [comment]
I would argue that any namespacing should be done by the user integrating this app into their own project, in the project level urls where they are included. Adding a namespace in the app forces you to abide by this namespace which can potentially cause conflict.

**Comment by wldcordeiro** [comment]
@JshWright It would but it's a simple fix and creates a cleaner URL pattern overall.

@SteveByerly if the patterns already resemble namespaced ones e.g. `account_login`, `account_signup` it doesn't make sense to not utilize the feature and in this case the user can still namespace the top-level url patterns like

```py
url(r'^users/', include('allauth.urls', namespace='users'))
```
then they can use the urls like

```py
reverse('users:account:signup')
```

**Comment by JshWright** [comment]
Personally I would be opposed to breaking changes in a point release, but I'm just a random contributor...

**Comment by wldcordeiro** [comment]
@JshWright This project hardly follows any form of semver.

**Comment by pennersr** [comment]
I am sorry, while probably cleaner, trading in an underscore for a colon does not bring any gains, but it would break a lot of installations. Without any clear benefit, this is really not worth it ...

**Pull request closed without merging**
