### PR TITLE
Fix some code quality and bug risk issues

### PR DESCRIPTION
**Pull request by pnijhara**
# Submitting Pull Requests

## General

 - [x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [x] All Python code must be 100% pep8 and isort clean.
 - [x] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [ ] If your changes are significant, please update `ChangeLog.rst`.
 - [x] Feel free to add yourself to `AUTHORS`.
 
 ## Provider Specifics
 
 In case you add a new provider:
 
- [ ] Make sure unit tests are available.
- [ ] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [ ] Add documentation to `docs/providers.rst`.
- [ ] Add an entry to the list of supported providers over at `docs/overview.rst`.

---
This PR focus on some code quality issues and made changes such as:
- Removing unnecessary generator
- Removing unnecessary comprehension
- Using literal syntax instead of function calls to create the data structure
- Fixing the dangerous default argument
---

Find the other issues found here - [https://deepsource.io/gh/pnijhara/django-allauth/issues/?category=recommended](https://deepsource.io/gh/pnijhara/django-allauth/issues/?category=recommended)

This PR also adds `.deepsource.toml` configuration file to run DeepSource analysis on the repo with. Upon enabling DeepSource, the analysis will run on every PR and commit to detect 560+ types of issues in the changes — including bug risks, anti-patterns, security vulnerabilities, etc.

To enable DeepSource analysis after merging this PR, please follow these steps:

1. [Signup](https://deepsource.io/signup/) on DeepSource with your GitHub account and grant access to this repo.
2. Activate analysis on this repo [here](http://deepsource.io/gh/pennersr/django-allauth).

You can also look at the [docs](https://deepsource.io/docs/guides/quickstart.html) for more details. Do let me know if I can be of any help!

### CODE REVIEW

**Comment by pennersr** [comment]
Sorry, but at this moment I would prefer not to start promoting yet another proprietary tool.

**Comment by pnijhara** [comment]
Thank you @pennersr
But what about the other changes? I can remove the DeepSource config file.

**Comment by pennersr** [comment]
Closed via 7d0766fe

**Comment by pnijhara** [comment]
Oh!
I was about to push the commit. Just saw the mail. Thank you @pennersr for considering the changes.

**Pull request closed without merging**
