### PR TITLE
Swappable SocialApp

### PR DESCRIPTION
**Pull request by yarbelk**
Make SocialApp swappable.  This should have no impact on existing installs.

This is currently at first pass with django 1.8 support (only tested on 1.8 ATM, haven't looked at other djangos yet).

Looking for feedback on how to improve this.  Note - its really rough right now and at the very least needs  a code cleanup (pep8 etc).

Also looking for feedback on older djangos (<1.8) and south migrations.

### CODE REVIEW

**Comment by pennersr** [comment]
I am curious to learn what your use case for this is. Could you elaborate a bit?

**Comment by yarbelk** [comment]
Sure. but Really Dont Merge it Yet even if its cool - this doesn't test both sides of the swapping (default and swapped).


I have busness logic that needs one-to-many (Product to SocialApp).  This is sort of related to issue #1002 By doing this, I can multiplex my providers based on information passed to me about a product.

By being able to swap out SocialApp I can side step most of the things I need to do to get multiple 'facebook' or 'g+' providers working, I only need to subclass the SocialLogin views to substitute the `current_app` logic.

Later I might put a more concerted effort into #1002 if it seems worthwhile.

**Comment by pennersr** [comment]
I think supporting multiple apps of the same kind could be taken care of without having to completely swap out the `SocialApp` model. Currently, the logic for choosing the `SocialApp` to use only takes the current site (as in contrib.sites) as input.  Suppose you could completely override the selection of the app the use, wouldn't that be sufficient for your use case?

**Comment by yarbelk** [comment]
Unfortunatly, They all are on the same domain, so that won't work.

**Comment by pennersr** [comment]
Still, even if they are all in the same domain, suppose this method was overridable in the adapter:

**Comment by yarbelk** [comment]
True - that lets you change the logic, but for this I'd need to create a join table, which since I'm migrating an existing user base of millions, I'd rather not have to manage (and join tables and normalization questions).

This being said, that is my fallback plan if I can't get the testing to work coherently.  There is no point of doing this if it doesn't benefit others, and no point of doing it if it can't be tested.

**Comment by yarbelk** [comment]
Gave up trying to swap out the model during the running tests, rather, I added different settings for swapped models, and rerun all the tests.

then I combine the output of the coverage for both.

**Comment by yarbelk** [comment]
Ok.  Tested, passing.

though the  only way to do this was run all the tests with the default SocialApp, and then rerun them with a swapped app (along with some special swapping tests). 

handled the coverage as well, combines the output of both.

**Comment by yarbelk** [comment]
Lets table this for now - I realized this is a larger kettle of ponies to boil that intended.

For this to really make sense, I need to be able to link more things together with relations than is currently possible.  As I need this locally, i'm implementing more of the swapability, and when everything works like happyness, I'll reopen this.

**Pull request closed without merging**
