### PR TITLE
Add support for SAML 2.0 

### PR DESCRIPTION
**Pull request by pennersr**
# Submitting Pull Requests

## General

 - [x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [x] All Python code must formatted using Black, and clean from pep8 and isort issues.
 - [x] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [x] If your changes are significant, please update `ChangeLog.rst`.
 - [x] If your change is substantial, feel free to add yourself to `AUTHORS`.

 ## Provider Specifics

 In case you add a new provider:

- [x] Make sure unit tests are available.
- [x] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [x] Add documentation to `docs/providers.rst`.
- [x] Add an entry to the list of supported providers over at `docs/overview.rst`.

### CODE REVIEW

**Comment by akx** [comment]
You might want to consider https://github.com/akx/smolsaml instead of onelogin.saml – it was born out of frustrations with the onelogin implementation (you can see a bunch of my PRs in the onelogin repo before I gave up)...

**Comment by pennersr** [comment]
The reason for going with `python3-saml` is that is smaller in scope compared to e.g. `pysaml2`, as the former focuses only on the SP side whereas the later covers both SP and IdP. But more importantly, `python3-saml` does have a lot of mileage, it is the SAML implementation used by e.g. Sentry as well. In the end, the SAML dependency is just an implementation detail of allauth. Would definitely want to switch to something smaller, but as it is now the mileage made by `python3-saml` is a deciding factor.

As for optional, definitely -- you will need to explicitly `pip install django-allauth[saml]` to pull this in.

**Comment by akx** [comment]
Yeah, I evaluated `pysaml2` too before deciding to write `smolsaml` for our (@valohai) uses. Anyway, glad it'll be optional – we had enough pains with various `xmlsec` versions...

**Comment by pennersr** [comment]
> Anyway, glad it'll be optional – we had enough pains with various xmlsec versions...

@akx It would be good if you could elaborate a bit on this point. I figured that `smolsaml`, `pysaml2` and `python3-saml` all depend on `xmlsec` so whatever installation trouble that gives, I would expect it to be the same for all these packages?

**Comment by akx** [comment]
@pennersr Yeah, I made the decision that smolsaml just shells out to the `xmlsec` tool for signing and verification because there have been notorious conflicts where different versions of libxml in the same python interpreter cause havoc (I'm out and about right now so I can't look up the issues) where things just don't work in a correct way.

**Pull request merged**
