### PR TITLE
Fix #2341

### LINKED ISSUE #2341: Password Reset form exposes registered E-Mails
The current reset form tells you if an address does not exist which is problematic if you are using your E-Mail to log in. By default you should get a message that an E-Mail was sent to that address regardless if the user exists or doesn't.

Would you be open for accepting a pull request for this issue?

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by mario** [comment]
@giant995 I don't mind changing this (will do it in an hour or two) but am not a fan of the terminology used.

**Comment by giant995** [comment]
I see why you're not a fan and I agree better words could be used. The idea is staying vague about the inner working of the system will reminding the user to provide a valid email otherwise they will never receive an answer.

**Comment by mario** [comment]
@giant995 updated. I'll open another PR once I have a suggestion for better wording.

**Comment by 9mido** [comment]
@mario Can you add onto this PR and do the same thing for signups? See issue 1307 for more info.

**Comment by mario** [comment]
@9mido I could, but I wonder what's the point when this PR has been sitting here ignore for ages?

**Comment by 9mido** [comment]
Yea I see what you mean @mario it can be frustrating to wait so long. 

I connected your PR to where the main issue 1307 is being tracked so it hopefully gets more attention. It seems the issue you originally connected to was closed because it was possibly a duplicate of 1307. 

Even some other core allauth PR feature/fixes is taking a while to merge :/

But if the demand for the community is high (which it is) it should eventually make it into the main library (at least we hope).

**Comment by pennersr** [comment]
This mentions it fixes #2341, but #2341 is not the whole story -- see #1307.  Eventually, when #1307 is fixed, you would always send an email to the user. For example, in case the email address is not known and you request a password reset, an email would be sent stating "You requested a password reset for email X, yet, we have no such account on file. Please signup ...".  So the current text, "We have sent you an e-mail..." would still be more approriate.

**Pull request closed without merging**
