### PR TITLE
added Provider meetup

### PR DESCRIPTION
**Pull request by abhishek-jaiswal**
added meetup provider

### CODE REVIEW

**Comment by pennersr** [comment]
Thanks. Could you have a look at these points?:

- [ ] Your changes contain pep8 issues, breaking the build. 
- [ ] Please add this provider to test_settings.py, overview.rst and installation.rst
- [ ] If you like, add yourself to the AUTHORS file

**Comment by abhishek-jaiswal** [comment]
can you please have a look into pull request

**Comment by abhishek-jaiswal** [comment]
can you look this

**Comment by jkabhishek** [comment]
Hi, When can I expect a release So, I can update it requirements.txt, for now, i am installing from git master

**Comment by pennersr** [comment]
You can use requirements.txt even without a release: https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source#16584935

**Comment by jkabhishek** [comment]
I am installing like that only from my master, but my client wants to be a pip link he is not happy with GitHub link, and he is not so technical so I can't argue with him so I just wanted to check from you

**Comment by pennersr** [comment]
FYI, 0.34.0 has been released

**Pull request merged**
