### PR TITLE
Two new providers: Onedrive & Box

### PR DESCRIPTION
**Pull request by btimby**
Added support for Onedrive and Box.

### CODE REVIEW

**Comment by btimby** [comment]
Sorry about my previous PR being included. If need be I can re-base this PR, or perhaps just merge it first.

**Comment by pennersr** [comment]
Can you add both providers to `test_settings.py` and `docs/overview.rst` ? Also don't forget to add yourself to AUTHORS...

**Comment by bittner** [comment]
@btimby Ben, can you address the improvement potential that @pennersr [has raised](https://github.com/pennersr/django-allauth/pull/1622#issuecomment-281012846)?

Then we could have this PR merged, and maybe we get a new release soon that includes these two [plus 3 other new providers](https://github.com/pennersr/django-allauth/compare/76df7ee...HEAD).

**Comment by btimby** [comment]
@bittner Yes, I will update the PR later today.

**Comment by pennersr** [comment]
I have added the Box provider. As for OneDrive, I don't think a separate provider is needed, we already have windowslive, can't you use/extend that one?

**Comment by btimby** [comment]
I did not realize when I started that Onedrive used live for auth, so yeah, live would suit my needs.

**Pull request closed without merging**
