### PR TITLE
Provider for23and me

### PR DESCRIPTION
**Pull request by Akay7**
Added provider for 23andMe

### CODE REVIEW

**Comment by pennersr** [comment]
Thanks. Can we rename the module to avoid this?:

    >>> from allauth.socialaccount.providers.23andme.views import *
      File "<stdin>", line 1
       from allauth.socialaccount.providers.23andme.views import *
                                              ^  
    SyntaxError: invalid syntax

`twenty3andme` or `twentythreeandme` ?

**Comment by pennersr** [comment]
Can you also add an entry for the provider over at `overview.rst`? Btw, don't forget to add yourself to the authors file.

**Comment by Akay7** [comment]
Okay I will do all necessary work, as soon as possible.

**Comment by Akay7** [comment]
I made necessary changes.

**Comment by pennersr** [comment]
Thanks. I made a small change so that the URLs look a bit cleaner (/23andme/ instead of /twentythreeandme/).

**Comment by Akay7** [comment]
Very good!!! Thank you for help

**Pull request merged**
