### PR TITLE
feat: Vendor OAuth1 from requests-oauthlib

### PR DESCRIPTION
**Pull request by akx**
## General

 - [x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [x] All Python code must formatted using Black, and clean from pep8 and isort issues.
 - [ ] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [ ] If your changes are significant, please update `ChangeLog.rst`.
 - [ ] If your change is substantial, feel free to add yourself to `AUTHORS`.

---

This PR vendors [the single file used from `requests_oauthlib`](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth1_auth.py) to avoid an extra dependency on `requests_oauthlib` itself. The only changes made to the vendored file are mechanical (isort, black) and adding the ISC license header from `requests-oauthlib`.

### CODE REVIEW

**Comment by akx** [comment]
No particular problem, was just looking at dependency chains while looking at routine upgrades for projects.

Seems a waste to have one extra 1K LoC dependency for the single file that's being used from it.

**Comment by pennersr** [comment]
I see that requests-oauthlib is also being used for OAuth2 purposes over at #3889 (which I still need to look into in detail btw).

**Comment by akx** [comment]
Welp, #3889 is apparently now closed 😅

**Comment by pennersr** [comment]
> Alternately, how about making requests-oauthlib an optional dependency for the integrations that still need OAuth1?

That would break backwards compatiblity. While possible, I don't see any real gain here. Let's skip this...

**Pull request closed without merging**
