### PR TITLE
Change provider registration to allow subclassing.

### PR DESCRIPTION
**Pull request by lukeburden**
Due to providers being registered in the same file as their definition
it is impossible to subclass a provider without having the parent be
registered. This change addresses this allowing for easy subclassing
of providers.

See #1632 for more info.

### CODE REVIEW

**Comment by lukeburden** [comment]
@pennersr is this ever so slight reduction in coverage a problem?

**Comment by pennersr** [comment]
Coverage is not a problem, it is hard failing on pep8/isort issues... Run make isort-fix

**Comment by lukeburden** [comment]
Coverage is the only problem I can see. I ran `make isort-fix`, it only adjusted some whitespace that was not related to my changes. Where are you seeing pep8 failures?

**Comment by lukeburden** [comment]
Coverage has only decreased as I've removed some lines of redundant but covered code, resulting in the ratio of covered to uncovered lines decreasing in a few files.

**Comment by pennersr** [comment]
I meant that coverage is not a problem in the sense that it breaks the build -- it is only a soft-failing indicator.

**Comment by pennersr** [comment]
Closes via 4039ab8e581d7e09ad354723d6dbe1c5d606db51

**Comment by bittner** [comment]
@lukeburden I've seen your note on subclassing in the [ChangeLog](https://github.com/pennersr/django-allauth/commit/4039ab8e581d7e09ad354723d6dbe1c5d606db51#diff-a136a3ab0403c35496be1955335be9d9R4).

I think it would be good to add a section on "Subclassing Providers" to the [Advanced Usage](https://django-allauth.readthedocs.io/en/latest/advanced.html) chapter of the docs, explaining the approach with appropriate code snippets.

I feel, especially the introduction of `provider_classes` deserves an explanation, because - with all the advantages of the changes - the code has now stopped to be self-explanatory.
``` python
provider_classes = [SomeProvider]
```
used to be:
``` python
providers.registry.register(SomeProvider)
```

**Comment by lukeburden** [comment]
@bittner Thanks for your comment. We could rename `provider_classes` to something a little more explicit like `discoverable_provider_classes`, potentially. It strikes me that anyone subclassing a provider would likely be:

1. basing their approach off an existing provider definition, in which case they'll see this convention
2. be familiar with the loading logic and so understand the convention

Changing the name would require a little more logic in the load method to still support the present naming; this doesn't seem worth it to me but will let @pennersr voice his thoughts.

On the special documentation for subclassing a provider; good idea, I'll do that.

**Pull request closed without merging**
