### PR TITLE
Improved Japanese translation

### PR DESCRIPTION
**Pull request by skyarrow87**
# Submitting Pull Requests

## General

 - [x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [x] All Python code must formatted using Black, and clean from pep8 and isort issues.
 - [ ] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [ ] If your changes are significant, please update `ChangeLog.rst`.
 - [ ] If your change is substantial, feel free to add yourself to `AUTHORS`.

 ## Provider Specifics

 In case you add a new provider:

- [x] Make sure unit tests are available.
- [ ] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [ ] Add documentation to `docs/providers.rst`.
- [ ] Add an entry to the list of supported providers over at `docs/overview.rst`.

### CODE REVIEW

**Comment by pennersr** [comment]
There is a `django.po` added to the `example` dir -- that is not needed. Can you drop it? Thanks.

**Comment by skyarrow87** [comment]
> There is a `django.po` added to the `example` dir -- that is not needed. Can you drop it? Thanks.

Sorry, I did it. Thank you.

**Comment by pennersr** [comment]
Can you also drop the changes to the nl .po file? Thanks.

**Comment by skyarrow87** [comment]
Sorry for the repetition. I have limited the changes to `allauth/locale/en/LC_MESSAGES/django.po` only.

**Pull request merged**
