### PR TITLE
Add Asana socialaccount provider

### PR DESCRIPTION
**Pull request by eranrund**
Pretty trivial :-)

### CODE REVIEW

**Comment by eranrund** [comment]
Thanks for merging, @pennersr. Any idea whne this would get released?

**Comment by eranrund** [comment]
Also - I forgot to add it to the Changelog. Might be worth mentioning this was added?

**Comment by pennersr** [comment]
Yes, an entry is needed there, also it should be added as an entry to `INSTALLED_APPS` in installation.rst, overview.rst, and you should be added to AUTHORS.

**Comment by eranrund** [comment]
Sounds good. Do you want me to submit a PR for that or will you commit it directly?

**Pull request merged**
