### PR TITLE
Add Basecamp provider

### PR DESCRIPTION
**Pull request by yrik**

### CODE REVIEW

**Comment by pennersr** [comment]
Thanks! Can you add the provider to the test_settings.py?

**Comment by yrik** [comment]
@pennersr  Thanks for notice, added it.

See strange error connected with python 3.2 support of coverage package.

**Comment by yrik** [comment]
Created pull request on coveragepy to fix this issue https://bitbucket.org/ned/coveragepy/pull-requests/69/remove-unnecessary-u-prefixes-for-better/diff

Temporary used direct link to fixed repo. With fixed repo all tests goes ok.
Should I specify coverage version from pypy to have this pull-request accepted?

**Comment by yrik** [comment]
Ned from coveragepy suggested to use version 3.7.1 of coverage. Specified it in .travis.yml and tests goes ok.

**Comment by pennersr** [comment]
Thanks!

**Pull request merged**
