### PR TITLE
Updated ja lang file.

### PR DESCRIPTION
**Pull request by k-brahma**
# Submitting Pull Requests

checked `python manage.py compilemessages -l ja` worked properly.

### CODE REVIEW

**Comment by k-brahma** [comment]
Locally tested `python manage.py compilemessages" after merged.

**Comment by pennersr** [comment]
Thanks. I cannot merged this due to conflicts, could you look into those?

**Comment by k-brahma** [comment]
Thanks for reply.
Just now I merged your main repository and pushed again so please check it.

**Comment by pennersr** [comment]
>  Just now I merged your main repository and pushed again so please check it.

It is still listed as having conflicts. Did you push?

**Pull request closed without merging**
