### PR TITLE
feat: Support Django 4.2

### PR DESCRIPTION
**Pull request by simkimsia**
# Submitting Pull Requests

## General

 - [x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [ ] All Python code must formatted using Black, and clean from pep8 and isort issues.
 - [ ] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [x] If your changes are significant, please update `ChangeLog.rst`.
 - [x] If your change is substantial, feel free to add yourself to `AUTHORS`.

This supersedes the PR #3289

### CODE REVIEW

**Comment by simkimsia** [comment]
between my first commit for this PR at https://github.com/pennersr/django-allauth/commit/cde333834858f0661eadedea2a9e173c452b95d2 and my latest at https://github.com/pennersr/django-allauth/commit/8fbd2662ba88b8e5e36cf722b3d85bead278b737, the master had a big change in terms of officially dropping support for Django 2.x

hence, I rebased my changes on those upstream changes at master, and then force-pushed.

**Comment by simkimsia** [comment]
Thank you for merging Raymond 🙏 @pennersr

**Comment by simkimsia** [comment]
Sorry just asking, @pennersr do you have an estimate of releasing a new version on pypi that supports Django 4.2? The last version on pypi was April 2023 for v0.54

**Comment by pennersr** [comment]
Likely, one or 2 months from now, but if you are in a hurry and the current main branch meets your needs, you can pip install that -- as part of pip installing you can even pinpoint a certain commit, so you can treat that just like a real release.

`pip install git+https://github.com/pennersr/django-allauth@COMMIT#egg=django-allauth`

**Pull request merged**
