### PR TITLE
Moving templates/base.html to templates/account/base.html

### PR DESCRIPTION
**Pull request by CodePint**
- prevents conflict between users base.html and allauth base.html
- see issue #370 for details

### CODE REVIEW

**Comment by craiga** [comment]
Any thoughts on this @pennersr ? I'd love to have this merged in.

**Comment by pennersr** [comment]
This would need a note about breaking backwards compatibility in `ChangeLog.rst`. Additionally, the `example` app needs to be updated to reflect these changes -- it still refers to the top-level "base.html",

**Comment by CodePint** [comment]
Hello,

Sorry not updating this PR, I  missed the update notification.
I have come back to it and made the changes requested. 

I think this is correct, can you confirm? 
I was a bit fuzzy on the details and had to reacquaint myself with the issue.

- added breaking change note to ```changelog.rst``` and reflected changes in the ```example`` app.

**Comment by CodePint** [comment]
Bumping this.

@ pennersr

**Comment by CodePint** [comment]
bump

**Comment by pennersr** [comment]
Closed via 739018bd

**Pull request closed without merging**
