### PR TITLE
feat(providers): Add Stocktwits as a provider

### LINKED ISSUE #2645: Add support for Stocktwits
python-social-auth supports Stocktwits but my project use django-allauth so it will be nice to have the support.

There are some more platforms like Wonderlist which are available in python-social-auth but missing in django-allauth, if we can have those added it will be great.

### PR DESCRIPTION
**Pull request by iarp**
Adds Stocktwits as an available oauth2 provider.

Resolves #2645 

# Submitting Pull Requests

## General

 - [x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [x] All Python code must be 100% pep8 and isort clean.
 - [x] If your changes are significant, please update `ChangeLog.rst`.
 
 ## Provider Specifics
 
 In case you add a new provider:
 
- [x] Make sure unit tests are available.
- [x] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [x] Add documentation to `docs/providers.rst`.
- [x] Add an entry to the list of supported providers over at `docs/overview.rst`.

### CODE REVIEW

**Comment by connectio** [comment]
Scope getting skipped.
I have added the required scope in settings.py as:

```
SOCIALACCOUNT_PROVIDERS = {
    "stocktwits": {
        "SCOPE": ["read", "watch_lists", "publish_watch_lists", "publish_messages", "direct_messages", "follow_users",
                  "follow_stocks"]
    }
}
```

When I try to access the api to call ```publish_messages``` with saved token I get following error:
```{'response': {'status': 403}, 'errors': [{'message': 'Insufficient scope permission'}]}```

**Comment by iarp** [comment]
What api url are you attempting to use on stocktwits?

**Comment by connectio** [comment]
I am using this api call:
https://api.stocktwits.com/developers/docs/api#messages-create-docs

**Comment by iarp** [comment]
Got it, i misread the docs when reading the oauth setup, i have a pr #2654 open for this.

**Pull request merged**
