### PR TITLE
Battle.net provider region fixes

### PR DESCRIPTION
**Pull request by jleclanche**

### CODE REVIEW

**Comment by jleclanche** [comment]
@pennersr ping

**Comment by pennersr** [comment]
pong :) Can you rename the commit messages according to https://github.com/fteem/git-semantic-commits ?  This is the sole reason I have not merged it yet... GH does not allow me to rename the commit message without squashing your two commits.

**Comment by jleclanche** [comment]
@pennersr Didn't see your ping. I don't understand what you mean by semantic commit messages; I prefix everything with the socialauth provider, isn't that what you want?

**Comment by pennersr** [comment]
It's just about the commit message, please follow this style:

https://seesparkbox.com/foundry/semantic_commit_messages

So I would expect something like: "fix(battlenet): Foo" and/or "feat(battlenet): Bar"

**Comment by jleclanche** [comment]
@pennersr Sorry for the delay. Updated the commit messages.

**Pull request merged**
