### PR TITLE
feat: ACCOUNT_SIGNUP_OPEN and ACCOUNT_NEW_ACCOUNTS_ACTIVE settings

### PR DESCRIPTION
**Pull request by olivierdalang**
This PR adds two settings, allowing to toggle `is_open_for_signup` (allowing to easily close new registrations) and `user.is_active` (allowing for manual activation of new accounts by admins).

I guess it's quite common to need to switch those, and subclassing `allauth.account.adapter.DefaultAccountAdapter` just for that is a bit cumbersome.

If you like the feature, I can write some tests.

### CODE REVIEW

**Comment by wgordon17** [comment]
It might also be beneficial to apply the `SIGNUP_OPEN` logic to https://github.com/pennersr/django-allauth/blob/4a9d07c512d0247f940262038b7258ea986e1e16/allauth/socialaccount/adapter.py#L176 as well.

**Comment by olivierdalang** [comment]
@wgordon17 is this (last commit) what you meant ?

Is this really wanted ? (I'm asking as to me it seems it makes it more complicated to change the behaviour, since subclassing `DefaultAccountAdapter` would not be enough anymore...).

If this is ok, please advise of next steps to get this merged.

Thanks !!

**Comment by wgordon17** [comment]
I apologize...it's been way too long to remember what on earth I was thinking 😂

But, I _think_ something along the lines of another option, `SOCIALACCOUNT_SIGNUP_OPEN`, was what I had in mind. You could default it to None, and then do something like

```python
    def is_open_for_signup(self, request, sociallogin):
        """
        Checks whether or not the site is open for signups.
        Next to simply returning True/False you can also intervene the
        regular flow by raising an ImmediateHttpResponse
        """
        if app_settings.SOCIALACCOUNT_SIGNUP_OPEN is None:
            return get_account_adapter(request).is_open_for_signup(request)
        else:
            return app_settings.SOCIALACCOUNT_SIGNUP_OPEN
```

This would at least give you the option to control socialaccount signups separately, otherwise it would just default to the current behavior...that way it doesn't affect any legacy expectations.

**Comment by wgordon17** [comment]
I'm also not a maintainer of this project...so I'm not sure what would be needed to get it merged 😞

**Comment by olivierdalang** [comment]
> I apologize...it's been way too long to remember what on earth I was thinking 😂
> 
> But, I _think_ something along the lines of another option, `SOCIALACCOUNT_SIGNUP_OPEN`, was what I had in mind. You could default it to None, and then do something like
> 
> ```python
>     def is_open_for_signup(self, request, sociallogin):
>         """
>         Checks whether or not the site is open for signups.
>         Next to simply returning True/False you can also intervene the
>         regular flow by raising an ImmediateHttpResponse
>         """
>         if app_settings.SOCIALACCOUNT_SIGNUP_OPEN is None:
>             return get_account_adapter(request).is_open_for_signup(request)
>         else:
>             return app_settings.SOCIALACCOUNT_SIGNUP_OPEN
> ```
> 
> This would at least give you the option to control socialaccount signups separately, otherwise it would just default to the current behavior...that way it doesn't affect any legacy expectations.

Ok I see what you mean. I find these two similar and interdependent settings make things a bit complicated/confusing, as most of the time, if you want to disable signup, you want to do it both for social accounts and for regular accounts. For now, I'll revert the commit and we'll see whatever the maintainer thinks (if he comes by at some point). Thanks for the detailed review though !

**Comment by wgordon17** [comment]
Sounds good! 👍 My use case was that I actually wanted to rely on _only_ social account login...and it would be nice to have this controllable in settings...but subclassing the default Adapter was easy enough.

**Comment by 9mido** [comment]
Linking the following issue since it relates:

https://github.com/pennersr/django-allauth/issues/345

**Comment by pennersr** [comment]
It's already easy enough to close down signup using the adapter. As the discussion in this PR shows, the changes here are also not fully trivial (e.g. the `True` / `False` / `None` issue). All in all, I don't think this is a problem we need to fix. Closing.

**Pull request closed without merging**
