### PR TITLE
feat(i18n): Added Uzbek translations

### PR DESCRIPTION
**Pull request by HBarotov**
# Submitting Pull Requests

I am a native Uzbek speaker. I am using this package in my projects, so I thought it would be a good idea to translate it for myself & other potential users.

## General

 - [x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [ ] All Python code must formatted using Black, and clean from pep8 and isort issues.
 - [ ] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [ ] If your changes are significant, please update `ChangeLog.rst`.
 - [ ] If your change is substantial, feel free to add yourself to `AUTHORS`.

 ## Provider Specifics

 In case you add a new provider:

- [ ] Make sure unit tests are available.
- [ ] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [ ] Add documentation to `docs/providers/<provider name>.rst` and `docs/providers/index.rst` Provider Specifics toctree.
- [ ] Add an entry to the list of supported providers over at `docs/overview.rst`.

### CODE REVIEW

**Comment by pennersr** [comment]
Thanks! Though, it seems to break the build:

```
Execution of msgfmt failed: /home/runner/work/django-allauth/django-allauth/allauth/locale/uz/LC_MESSAGES/django.po:619:9: syntax error
/home/runner/work/django-allauth/django-allauth/allauth/locale/uz/LC_MESSAGES/django.po:619: keyword "Sizga" unknown
/home/runner/work/django-allauth/django-allauth/allauth/locale/uz/LC_MESSAGES/django.po:715:2: syntax error
/home/runner/work/django-allauth/django-allauth/allauth/locale/uz/LC_MESSAGES/django.po:715: keyword "Siz" unknown
/home/runner/work/django-allauth/django-allauth/allauth/locale/uz/LC_MESSAGES/django.po:1306:9: syntax error
/home/runner/work/django-allauth/django-allauth/allauth/locale/uz/LC_MESSAGES/django.po:1306: keyword "last_used" unknown
```

Can you look into those?

**Comment by HBarotov** [comment]
Yeah, sorry the issue was I somehow confused double quotes and similar-looking Unicode quotes. The issue is fixed now.

**Comment by pennersr** [comment]
Thanks, there is one more though:

```
django.po:976: 'msgstr' is not a valid Python format string, unlike 'msgid'. Reason: In the directive number 1, the character 'k' is not a valid conversion specifier.
```

**Comment by HBarotov** [comment]
Yeah, sorry for the less-than-acceptable work, the second time opening up a PR.

**Comment by pennersr** [comment]
No worries, thanks for contributing.

**Pull request merged**
