### PR TITLE
fix: updating the twitch provider to use new authentication API

### PR DESCRIPTION
**Pull request by MattBroach**
# What

Updates the `twitch` provider to user the new API's authentication framework.  This is still OAuth2-based, but uses a different set of authentication URLs and has completely changed the user data and content.

# Why

Although the previous API still technically works, the V5 API has been deprecated and could therefore be turned off at any time (it was actually supposed to be removed at the end of 2018, but, for now, has been granted a zombie status).  From Twitch's dev docs:

> Note: URLs have been updated to replace https://api.twitch.tv/kraken with https://id.twitch.tv. Code that uses the old kraken domain for Twitch authentication will continue to work until the removal of Twitch API v. 5 functionality. Twitch API v. 5 is currently deprecated.

# Caveats

The new API's post-login profile data is different in both structure and content than the old `V5` endpoint.  Although logins should function seamlessly when transitioning from the old API to the new one, any project that relies on data from 'SocialAccount.extra_data` should refer to the new API [user endpoint](https://dev.twitch.tv/docs/api/reference/#get-users) documentation for information on the new profile data format and content.

# Submitting Pull Requests

## General

 - [x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [x] All Python code must be 100% pep8 and isort clean.
 - [x] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [x] If your changes are significant, please update `ChangeLog.rst`.
 - [x] Feel free to add yourself to `AUTHORS`.
 
 ## Provider Specifics
 
 In case you add a new provider:
 
- [x] Make sure unit tests are available.
- [x] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [x] Add documentation to `docs/providers.rst`.
- [x] Add an entry to the list of supported providers over at `docs/overview.rst`.

### CODE REVIEW

**Comment by MattBroach** [comment]
I had to do a number of additional commits to deal with some lingering Travis errors.  Would the preference be for me to close this PR, squash the commits, and open a new PR with a single commit?  I'd be happy to do whatever makes the maintainers happiest.

**Comment by pennersr** [comment]
Thanks. Can you add the "Caveats" to the ChangeLog.rst (Backwards incompatible changes) ?

**Comment by MattBroach** [comment]
Changelog updated!

**Comment by pennersr** [comment]
Merged via 72b6cd5

**Comment by beheh** [comment]
Based on my tests the default scope needs to be either updated or removed. The email scope for the new endpoint is now `user:read:email`, but it's not required for just authenticating with Twitch. [List of scopes](https://dev.twitch.tv/docs/authentication/#scopes).

**Comment by MattBroach** [comment]
Whoops, that's correct -- the old V5 scope didn't get updated.  I think my personal preference would be to add the updated `user:read:email` scope rather than omit it -- it's true that it isn't required, but I think most people building Django apps would want the access to the email address (for password resets and such).  But I'm not wedded to it...

**Comment by beheh** [comment]
Yeah, right, it should probably be included, I think that's what most providers do. While we don't need it in our app we can always override the scope.

**Pull request closed without merging**
